### ISSUE TITLE
java.net.BindException error upon opening GUI

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1249]
@aymanhab, found this on trying the latest build:

On Win 10, OpenSim 4.2-2020-12-18-04a2d38:

Upon ~~first opening the GUI after install~~ opening the GUI (happens every time I open the GUI), I noticed a red error bubble in the bottom right. Below is info from the error:
![image](https://user-images.githubusercontent.com/7455790/102667163-998e9180-413d-11eb-8df0-ff71ea70739a.png)

```
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:461)
	at sun.nio.ch.Net.bind(Net.java:453)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:384)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[catch] at org.eclipse.jetty.JettyMain.startServer(JettyMain.java:101)
	at org.eclipse.jetty.JettyMain.main(JettyMain.java:68)
	at org.opensim.view.pub.ViewDB$1VizWorker.construct(ViewDB.java:1310)
	at org.opensim.swingui.SwingWorker$2.run(SwingWorker.java:130)
	at java.lang.Thread.run(Thread.java:748)
```

[messages.log](https://github.com/opensim-org/opensim-gui/files/5718368/messages.log)

**Comment by aymanhab** [comment]
This happens if another instance of the application is running since
they'll use same port. Please close other instances first.

**Comment by carmichaelong** [comment]
Bah, thanks. I missed the other open window.
