### ISSUE TITLE
Loading Hamner2010.osim: exception in updAbstractPropertyByIndex()

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#190]
Loading Hamner2010.osim and attempting to use the marker set leads to exceptions with the PropertyTable (see two different stack traces below).

```
java.lang.RuntimeException: PropertyTable::updAbstractPropertyByIndex(): index 324 out of range (-765295312 properties in table).
	at org.opensim.modeling.opensimActuatorsAnalysesToolsJNI.OpenSimContext_replaceMarkerSet(Native Method)
	at org.opensim.modeling.OpenSimContext.replaceMarkerSet(OpenSimContext.java:265)
	at org.opensim.tracking.ScaleToolModel.resetMarkers(ScaleToolModel.java:602)
	at org.opensim.tracking.ScaleToolModel.loadExtraMarkerSet(ScaleToolModel.java:594)
	at org.opensim.tracking.ScaleToolModel.loadSettings(ScaleToolModel.java:948)
	at org.opensim.tracking.ScaleToolPanel.loadSettings(ScaleToolPanel.java:285)
	at org.opensim.tracking.BaseToolPanel$LoadSettingsAction.actionPerformed(BaseToolPanel.java:70)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This one occurred after selecting a file for "Marker data for static pose":
```
java.lang.RuntimeException: PropertyTable::getAbstractPropertyByIndex(): index 13 out of range (0 properties in table).
	at org.opensim.modeling.opensimSimulationJNI.Model_getMarkerSet(Native Method)
	at org.opensim.modeling.Model.getMarkerSet(Model.java:1287)
	at org.opensim.tracking.ScaleToolPanel.updateFromModel(ScaleToolPanel.java:202)
	at org.opensim.tracking.ScaleToolPanel.update(ScaleToolPanel.java:174)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.opensim.tracking.ScaleToolModel.setModified(ScaleToolModel.java:508)
	at org.opensim.tracking.ScaleToolModel.update(ScaleToolModel.java:483)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.opensim.tracking.IKCommonModel.setModified(IKCommonModel.java:73)
	at org.opensim.tracking.IKCommonModel.setTimeRange(IKCommonModel.java:179)
	at org.opensim.tracking.IKCommonModel.setMarkerDataFileName(IKCommonModel.java:122)
	at org.opensim.tracking.ScaleToolPanel.staticTrialFileNameStateChanged(ScaleToolPanel.java:866)
	at org.opensim.tracking.ScaleToolPanel.access$400(ScaleToolPanel.java:60)
	at org.opensim.tracking.ScaleToolPanel$7.stateChanged(ScaleToolPanel.java:399)
	at org.opensim.swingui.FileTextFieldAndChooser.fireStateChanged(FileTextFieldAndChooser.java:179)
	at org.opensim.swingui.FileTextFieldAndChooser.setFileName(FileTextFieldAndChooser.java:110)
	at org.opensim.swingui.FileTextFieldAndChooser.setFileName(FileTextFieldAndChooser.java:115)
	at org.opensim.swingui.FileTextFieldAndChooser.browseButtonActionPerformed(FileTextFieldAndChooser.java:231)
	at org.opensim.swingui.FileTextFieldAndChooser.access$300(FileTextFieldAndChooser.java:41)
	at org.opensim.swingui.FileTextFieldAndChooser$4.actionPerformed(FileTextFieldAndChooser.java:287)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

These exceptions are similar to one reported for the NIPS challenge: https://github.com/stanfordnmbl/osim-rl/issues/20

**Comment by jenhicks** [comment]
I was able to load the model from the simtk project page:
https://simtk.org/frs/?group_id=516
And run scale from the given scale setup file. 

There is an issue with visualizing the trunk due to an error loading the vtp file, but I believe there is a separate issue for this.

Tested on Windows 10

**Comment by chrisdembia** [comment]
@jenhicks what about if you manually select a file for "Marker data for static pose" before running the scale tool?

**Comment by jenhicks** [comment]
Model also loads and scales on Mac. I tried manually selecting a file for "Marker data for static pose" and still no issues.
