### ISSUE TITLE
"Blockage message pending 10000 for BLOCKING"

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#233]
Opening the GUI (with embedded browser) and opening arm26 led to this exception on macOS:

```
java.lang.IllegalStateException: Blocking message pending 10000 for BLOCKING
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.lockMsg(WebSocketRemoteEndpoint.java:130)
	at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendString(WebSocketRemoteEndpoint.java:379)
	at org.eclipse.jetty.VisWebSocket.sendVisualizerMessage(VisWebSocket.java:75)
	at org.eclipse.jetty.WebSocketDB.broadcastMessageJson(WebSocketDB.java:67)
	at org.opensim.view.pub.ViewDB.updateModelDisplay(ViewDB.java:1289)
	at org.opensim.view.pub.ViewDB.updateModelDisplay(ViewDB.java:1270)
	at org.opensim.coordinateviewer.CoordinateViewerTopComponent.componentOpened(CoordinateViewerTopComponent.java:393)
	at org.opensim.coordinateviewer.CoordinateViewerTopComponent.update(CoordinateViewerTopComponent.java:443)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.opensim.view.pub.OpenSimDB.setCurrentModel(OpenSimDB.java:260)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:152)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:139)
	at org.opensim.view.FileOpenOsimModelAction$1.run(FileOpenOsimModelAction.java:95)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

However, the model did visualize in a browser window, and clicking "Reload" for the jxbrowser caused the model to also show up in the embedded browser.

**Comment by aseth1** [comment]
@aymanhab which PR addressed this issue?
@chrisdembia are seeing this anymore?

**Comment by chrisdembia** [comment]
@aseth1 no I am no longer seeing this issue. Consider this issue verified! I'm closing this issue (is that what I'm supposed to do?)
