### ISSUE TITLE
Adding/Deleting PathPoint of GeometryPath fails when it has wrapping surfaces

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#303]
Using the GeometryPath editor (via Properties editor for a Muscle's GeometryPath) adding or removing a PathPoint causes exceptions. Requires saving the edited model, quitting the GUI, deleting the JXBrowswser cache, relaunching GUI and reloading to see the change.

Exception:
```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
	at org.opensim.threejs.JSONMessageHandler.convertLocationStringToPropertyFormat(JSONMessageHandler.java:71)
	at org.opensim.threejs.JSONMessageHandler$1.run(JSONMessageHandler.java:37)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1086)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1136)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1108)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:131)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
	at org.openide.util.Mutex.readAccess(Mutex.java:218)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1093)
	at java.awt.Component.show(Component.java:1673)
	at java.awt.Component.setVisible(Component.java:1625)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.openide.explorer.propertysheet.CustomEditorAction.actionPerformed(CustomEditorAction.java:325)
	at org.openide.explorer.propertysheet.SheetTable.editCellAt(SheetTable.java:1135)
	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1108)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1038)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6532)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at org.openide.explorer.propertysheet.SheetTable.processMouseEvent(SheetTable.java:833)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jenhicks** [comment]
This does not appear to be fixed for me. 

Take gait10dof18musc
Show only soleus_r
Add a path point at the beginning
The muscle disappears from the visualizer.
Delete the path point
The muscle is still not visualized

**Comment by jenhicks** [comment]
I am able to add and delete pathpoints.

Some questions/potential issues:
- I can't select and move any pathpoints while I'm in edit mode. Is this expected?
- Do the selection check boxes have any purpose?
- I got a crash when I hit the "Restore" button. I'll send the report.

**Comment by jimmyDunne** [comment]
I am seeing similar issues to Jen. 

If you add a new pathpoint, the point is expressed in isn't clear. Even when you copy the location of the another point, the new point won't overlay. 

![ezgif com-video-to-gif 7](https://user-images.githubusercontent.com/5296507/40862144-6ae6795e-65a0-11e8-996c-23e5e5dc2456.gif)

**Comment by jimmyDunne** [comment]
OpenSim 4.0 

![ezgif com-video-to-gif 9](https://user-images.githubusercontent.com/5296507/40862962-0ff5bd54-65a3-11e8-9f19-ec503b1db608.gif)

**Comment by tkuchida** [comment]
> Do the selection check boxes have any purpose?

In 3.3, checking a box highlights the corresponding path point in the visualizer, which is very helpful when inspecting muscle paths.

![](https://user-images.githubusercontent.com/4203505/40902011-5174c23a-6787-11e8-84a8-e24f95e53d8b.png)

**Comment by aymanhab** [comment]
True, @tkuchida except that we now can select at most one pathpoint so we want to make sure that selecting one deselect others. The PathEditor is a modal dialog since 3.3 so you can't graphically edit  while dialog is up but you can select, close then drag. Typically users either have specific values to type/copy-paste in dialog or drag then check the numbers in dialog.

**Comment by tkuchida** [comment]
> Typically users either have specific values to type/copy-paste in dialog or drag then check the numbers in dialog.

My use case was different: I was trying to understand which muscle path points were malfunctioning. I suspect a user would encounter a similar use case during model building. It would have been much easier if a sphere highlighted in the Visualizer when I selected one of the points. I recommend moving these properties into the Properties panel with the other properties for consistency, interactivity with the Visualizer, enabling undo/redo, etc.

**Comment by aseth1** [comment]
> This is fixed with PR #858 except for restore functionality which is covered by issue #817 already

What is fixed exactly? The use case @tkuchida describes is still a problem in OpenSim_9c841136-2018-06-27. 

One cannot graphically select a muscle so I am forced to use the navigator and find muscles. If you were hoping to use OpenSim to learn something about anatomy that just got a lot harder. Furthermore, selecting a muscle in the navigator does not highlight a muscle so I have to open the geomtrypath (...) to select path points to get a correspondence between the drawn muscle and its name in the navigator list. Then, when you finally have the muscle and point you want to edit you get the selectable frame you can drag in the Visualizer. How ironic it is then that you then cannot use the frame to edit the path without closing the GeomtryPath modal window first and then you have to open and it again to see the changed value.  Can we just not make the window modal anymore?

**Comment by aseth1** [comment]
I can add a path point! But the path now ignores the wrapping object.

![image](https://user-images.githubusercontent.com/6494122/43172613-eb851370-8f64-11e8-8413-5ef66652a408.png)

Also, when I press restore it appears to remain as an orphaned point.

![image](https://user-images.githubusercontent.com/6494122/43170516-62a0ca22-8f5a-11e8-9688-e308c1245541.png)

I tried this again closing the model and reloading. This time I get a remnants of the muscles that wrapped over the wrap object along with straight line paths for not gastroc heads. It is as if gastroc wrap object were removed or disabled.

![image](https://user-images.githubusercontent.com/6494122/43172764-dadcbc7a-8f65-11e8-9729-e8d5dcef439c.png)

I am not sure what is going on here. This is on Windows OpenSim_cea85df3-2018-07-18. I am moving it back to Next up.

**Comment by aymanhab** [comment]
@aseth1 Here's the summary of the issues involved since we didn't discuss after the meeting:
Path edits are made of two parts: 

- a. API changes to add/remove pathpoints/wrapping/.. 
- b. Visualization changes to reflect the change in path

In the past in 4.0 I tried to do b. incrementally. This works without wrapping but fails with wrapping since "intermediate" points may need to be added/removed and interactions are more complicated. I'm changing this to recreate visualization completely on edit which we know we can do successfully because without editing path visualization works as expected. Hope this helps.

**Comment by aymanhab** [comment]
My conjecture was that the issue had to do with adding new pathpoints that fell inside wrapping. Since this has been fixed by https://github.com/opensim-org/opensim-core/pull/2268 and other editing operations were fixed by https://github.com/opensim-org/opensim-gui/pull/967 and what I tried worked as expected, it would be great to have another pair of eyes check if there're still issues with editing paths with wrapping in latest build: 
@carmichaelong @nickbianco @chrisdembia or @jenhicks

**Comment by chrisdembia** [comment]
I no longer see the issues @aseth1 mentioned (orphaned point).

**Comment by carmichaelong** [comment]
Tested on W10 with OpenSim 4.0-2018-08-27-ae111a49. Used the Rajagopal model from the models repo and checked on gas_lat_r using the parameters @aseth1 used. I also did not see the issues mentioned. Separately, however, each change (e.g., add point, delete point, move point) did take some time between applying the change and visualizing in the GUI (~5-10 seconds).

**Comment by chrisdembia** [comment]
> each change (e.g., add point, delete point, move point) did take some time between applying the change and visualizing in the GUI (~5-10 seconds).

I had a slight delay too; not quite 10 seconds.
