### ISSUE TITLE
Deadlock when doing File > Open Model... on fresh machine

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#306]
This occurs when the computer has no preferences for OpenSim (launching app after running `defaults delete org.opensim.utils` in a terminal.

Here's a jstack stack trace that specifies the deadlock:

```
Found one Java-level deadlock:
=============================
"Module-Actions":
  waiting to lock monitor 0x00007ff68ccb97d8 (object 0x00000007af576be0, a java.lang.Object),
  which is held by "AWT-EventQueue-0"
"AWT-EventQueue-0":
  waiting to lock monitor 0x00007ff68ccb9728 (object 0x0000000780198dc8, a java.awt.Component$AWTTreeLock),
  which is held by "Module-Actions"

Java stack information for the threads listed above:
===================================================
"Module-Actions":
        at com.apple.laf.AquaFileSystemModel.getRowCount(AquaFileSystemModel.java:194)
        - waiting to lock <0x00000007af576be0> (a java.lang.Object)
        at javax.swing.JTable.getRowCount(JTable.java:2662)
        at javax.swing.plaf.basic.BasicTableUI.createTableSize(BasicTableUI.java:1692)
        at javax.swing.plaf.basic.BasicTableUI.getPreferredSize(BasicTableUI.java:1733)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
        at javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:495)
        at java.awt.Container.preferredSize(Container.java:1794)
        - locked <0x0000000780198dc8> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.getPreferredSize(Container.java:1778)

...

"AWT-EventQueue-0":
        at java.awt.Component.invalidate(Component.java:2921)
        - waiting to lock <0x0000000780198dc8> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.invalidate(Container.java:1585)
        at javax.swing.JComponent.revalidate(JComponent.java:4857)
        at javax.swing.JTable.tableRowsInserted(JTable.java:4482)
        at javax.swing.JTable.tableChanged(JTable.java:4407)
        at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
        at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
        at com.apple.laf.AquaFileSystemModel$DoChangeContents.run(AquaFileSystemModel.java:458)
        - locked <0x00000007af576be0> (a java.lang.Object)
        - locked <0x00000007af5fc758> (a java.lang.Object)

```

[mac_hang_on_file_open_model_jstack.txt](https://github.com/opensim-org/opensim-gui/files/1154515/mac_hang_on_file_open_model_jstack.txt)

**Comment by aseth1** [comment]
@chrisdembia @carmichaelong can you confirm that you are not experiencing this issue anymore.

**Comment by chrisdembia** [comment]
I no longer have this issue.

**Comment by carmichaelong** [comment]
Seems to be no issue for me either.

**Comment by chrisdembia** [comment]
Cool. Verified ✔️
