### ISSUE TITLE
[MAC] Visualizer Window no longer opens

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#450]
After working in the GUI for an hour, the Visualizer is no longer opening in the GUI. The error says that jxBrowserTopComponent cannot be found. 

![screen shot 2017-11-20 at 1 49 49 pm](https://user-images.githubusercontent.com/5296507/33043368-1896b814-cdfa-11e7-9a21-eaee00402ba7.png)

**Comment by aymanhab** [comment]
Will investigate

**Comment by jimmyDunne** [comment]
The above issue was in the previous version, however, this issue seems to be persistent in the latest Beta build. When trying to open the visualizer through Window->Visualizer the following exception is sent;

`java.lang.IllegalStateException: Cannot find TopComponent with preferredID jxBrowserTopComponent, see IDE log for more details.
	at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:92)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by aymanhab** [comment]
The component not found is a downstream effect of the JxBrowser failing to start/launch. Likely this is due to jxbrowser cache that wasn't cleared. The cache is stored in  "user's temp directory" per documentation. I'd suggest you check your temp directory and remove any jxbrowser or chromium folders and retry.

**Comment by jimmyDunne** [comment]
> The cache is stored in "user's temp directory" per documentation.

Can you point me to this documentation? Do you mean our documentation or JxBrowsers?

From advice from Chris, I was able to get the visualizer working;
(1) Deleted Library/Application Support/OpenSim
(2) Deleted the OSIM4.0 folder from applications
(3) Reinstalled OSIM4.0
(4) Deleted the jxbrowser files from /var (they got put in there again)

**Comment by aymanhab** [comment]
The documentation I was referring to is JxBrowser's. (online), we maybe
able to disable caching if that proves to be the issue and appears common
(not reported by any other user/tester on osx)
I don't think you needed to do anything but (4).

Keep an eye and if that happens again we can investigate further.

**Comment by chrisdembia** [comment]
We tried doing only (4) and this wasn't sufficient. Maybe we needed to wait a while?

**Comment by aymanhab** [comment]
If there's a running process that may be a problem, but 1-4 feels like a
big hammer. Will see next time.

**Comment by jimmyDunne** [comment]
This problem is continuing. The visualizer no longer opens (again), and performing the steps above does not fix the issue. On each opening of the GUI, the jxbrowser files are re-printed into /var, so deleting them does nothing. Deleting Library/Application Support/OpenSim and re-installing also does nothing.

**Comment by aymanhab** [comment]
Can you make sure to kill any running jxbrowser, opensim or chromium processes before restart?

**Comment by jimmyDunne** [comment]
yep, no processes running. re-started the whole system a number of times to make sure.

**Comment by aymanhab** [comment]
Are there Chromium files under /var? Timestamp may help tell what other files if any.

**Comment by chrisdembia** [comment]
User experience and feedback session (EUFS): Hannah had this issue (first time installing OpenSim on macOS Sierra):

```
java.lang.IllegalStateException: Cannot find TopComponent with preferredID jxBrowserTopComponent, see IDE log for more details.
	at org.openide.windows.OpenComponentAction.actionPerformed(OpenComponentAction.java:92)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

She was able to get the visualizer to load by simply restarting the GUI.

Note that Hannah also had issues with the GUI freezing (while the "install resources" dialog was open) the first time she launched the GUI.

Mac OpenSim 2416f17-2018-02-25

**Comment by chrisdembia** [comment]
We might be able to google solutions for this: https://www.google.com/search?client=safari&rls=en&q=java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege+jxbrowser&ie=UTF-8&oe=UTF-8

**Comment by jenhicks** [comment]
This is fixed for you now, correct @jimmyDunne ?

**Comment by jimmyDunne** [comment]
I had no movement on this and so spent some time over the weekend going through the jxbrowser help forums trying out candidate fixes. Eventually, (I hope) I found a permanent fix (in such that both my Macs can now have the visualizer opening everytime I re-open OpenSim 4.0).

What was probably happening is that the chromium server was being denied or hitting an exception and any this wasn't making its way up to GUI. This seems to have been fixed by explicitly allowing the jx-browser chromium application access through the Mac firewall.

![image](https://user-images.githubusercontent.com/5296507/39136770-d7456fa4-46d0-11e8-9228-4ee595b53331.png)

I am not sure why had this issue when no other Mac user did. Since this happened on two MacBooks that I own, it must be something to do with the particular security settings that I use. Perhaps the Stanford security software adjusts things on my machine that I am unaware of. 

This type of problem will need to be documented somewhere, so I will add a documentation tag to this issue and close once I have something written in Confluence.

**Comment by chrisdembia** [comment]
It's great to have figured out this issue!

**Comment by jimmyDunne** [comment]
Okay, so an update. The firewall issue wasn't the problem. I restarted my machine and the visualizer wouldn't open again. I had closed some programs on my previous test so I started to iterate testing particular background processes that reopen at startup. 

The culprit was [RescueTime](https://www.rescuetime.com/). RescueTime is behavior tracking software that logs all the time you spend on apps and websites and gives you reports on your productivity. 

This was hard to figure out because if you close RescueTime, open OpenSim 4.0 (visualizer works), close OpenSim 4.0, reopen RescueTime, and reopen OpenSim 4.0 the visualizer continues to work. The original bug only occurs if RescueTime is open on startup and then you try to open OpenSim. At that point, the visualizer will never open until you close RescueTime.  

Since this was a software conflict, there may be other apps out there that could cause this problem.

**Comment by chrisdembia** [comment]
So weird!!

**Comment by gizemozd** [comment]
@jimmyDunne, thank you for finding this out! 
I was having exactly the same problem with OpenSim 4.4 in macOS Monterey, and RescueTime was the culprit.

**Comment by cheersSZ** [comment]
I encountered the same jxBrowserTopComponent error on my M5 Mac, even though I didn't have RescueTime installed.

The issue seems to be caused by macOS Gatekeeper/App Translocation, which puts the app in a "read-only" sandbox and prevents the Visualizer's IPC (Inter-Process Communication) from starting.

My Solution:

1.Open Terminal and run the following command to remove the quarantine attribute:
```
sudo xattr -rd com.apple.quarantine /Applications/OpenSim\ 4.5.app
```
(Make sure to replace the path with your actual installation directory).

2.Clear the broken cache/config folder:
Delete ~/Library/Application Support/OpenSim/4.5
