### ISSUE TITLE
Installing resources: On Mac, APIExamples and Scripts folders are empty

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#501]

**Comment by aymanhab** [comment]
Seen that on Blanca's machine. Since users don't need to look inside the App for APIExamples and Scripts they should live in same relative path on Windows and OSX. Now that's not the case. The installResources dialog looks for the folders:
Models and sdk/APIExamples, sdk/Scripts in same top level folder on Windows, while layout on osx is different

**Comment by chrisdembia** [comment]
@aymanhab it sounds like we need to meet again to reevaluate the layout of files on Mac.

**Comment by aymanhab** [comment]
Sure, tomorrow would work if you're available.

**Comment by chrisdembia** [comment]
Yes I am.

**Comment by chrisdembia** [comment]
This might be why: I get the following Java exception

```
java.nio.file.FileAlreadyExistsException: /Users/chris/Documents/OpenSim40/Models/Gait10dof18musc/CMC/walk_Setup_CMC.xml
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at org.opensim.utils.FileUtils$2.visitFile(FileUtils.java:583)
	at org.opensim.utils.FileUtils$2.visitFile(FileUtils.java:573)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.opensim.utils.FileUtils.copyFiles(FileUtils.java:573)
[catch] at org.opensim.utils.TheApp.installResources(TheApp.java:225)
	at org.opensim.view.Installer.restorePrefs(Installer.java:137)
	at org.opensim.view.Installer.restored(Installer.java:98)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:468)
	at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:391)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:102)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:343)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:437)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:519)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:421)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:441)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:340)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1365)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1170)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
	at org.netbeans.core.startup.Main.start(Main.java:307)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by chrisdembia** [comment]
Verified fixed.
