### ISSUE TITLE
Running RRA with Sam Hamner's data without running IK first causes StageTooLow

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#562]
### Steps to reproduce

1. Download https://simtk.org/frs/download_confirm.php/file/2512/RunningSimulation_simTK.zip?group_id=516
2. Open subject 2 scaled model.
3. Run the RRA setup file using the IK results already provided (do not run IK in the GUI) (might have to update some of the input files (external loads).)

### Expected result

RRA runs.

### Actual result

Red circle exception:

```
java.lang.RuntimeException: SimTK Exception thrown at State.cpp:964:
 Expected stage to be at least Acceleration in getCacheEntry but current stage was Velocity
	at org.opensim.modeling.opensimActuatorsAnalysesToolsJNI.Kinematics_begin(Native Method)
	at org.opensim.modeling.Kinematics.begin(Kinematics.java:100)
	at org.opensim.view.motions.JavaMotionDisplayerCallback.createResultStorage(JavaMotionDisplayerCallback.java:107)
	at org.opensim.view.motions.JavaMotionDisplayerCallback.<init>(JavaMotionDisplayerCallback.java:132)
	at org.opensim.tracking.RRAToolModel$RRAToolWorker.<init>(RRAToolModel.java:103)
	at org.opensim.tracking.RRAToolModel.execute(RRAToolModel.java:371)
	at org.opensim.tracking.AnalyzeAndForwardToolPanel.pressedApply(AnalyzeAndForwardToolPanel.java:620)
	at org.opensim.tracking.BaseToolPanel.actionPerformed(BaseToolPanel.java:128)
	at org.netbeans.core.windows.services.NbPresenter$ButtonListener.actionPerformed(NbPresenter.java:1398)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
### Environment and GUI version

Mac (Rachel Jackson) and Windows (Nick Bianco) OpenSim 2416f17-2018-02-25

**Comment by aymanhab** [comment]
GUI uses Kinematics analysis internally to record/save motion for playback purposes. Kinematics analysis records acceleration by defaults. Turning this option off explicitly.

**Comment by chrisdembia** [comment]
I think the fix is for the Kinematics analysis to realize to Acceleration internally.

**Comment by aymanhab** [comment]
That will work too but is unnecessary computation since the gui doesn't use the resulting accelerations anyway.

**Comment by chrisdembia** [comment]
Sorry I didn't see your reply here before I responded to #566. Is this kinematics analysis not the one used to write kinematics STO files to the results directory?

**Comment by aymanhab** [comment]
Nope @chrisdembia this is aded by GUI since most tools do not add kinematics analysis of their own.

**Comment by jenhicks** [comment]
I'm not seeing this issue. However, I'm running RRA without an external loads file specified.
