### ISSUE TITLE
Double-clicking bodies in "topology view" works only once per body

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#575]
### Steps to reproduce
- open arm26 model
- *Window* menu > *Topology View*
- double-click "r_humerus" box -> "r_humerus" body is selected in the Navigator, as expected
- double-click "r_ulna_radius_hand" box -> "r_ulna_radius_hand" body is selected in the Navigator, as expected
- double-click "r_humerus" box

### Expected result
"r_humerus" body is selected in the Navigator

### Actual result
Nothing happens. If the model is then closed, the GUI reports a red-circle error (`NullPointerException`) when the model is opened again:
<pre>
java.lang.NullPointerException
	at org.opensim.view.pub.ViewDB.markSelected(ViewDB.java:1022)
	at org.opensim.view.pub.ViewDB.clearSelectedObjects(ViewDB.java:1159)
	at org.opensim.view.pub.ViewDB.update(ViewDB.java:340)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.opensim.view.pub.OpenSimDB.setCurrentModel(OpenSimDB.java:264)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:156)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:143)
	at org.opensim.view.FileOpenOsimModelAction$2.run(FileOpenOsimModelAction.java:98)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>

### Environment and GUI version
AppVeyor artifact OpenSim-6826a797-2018-02-28.zip

**Comment by jimmyDunne** [comment]
Fixed on W10. OpenSim-a0d644b3-2018-05-04.zip
