### ISSUE TITLE
Gait2354: Running Forward Tool with results of CMC fails

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#585]
### Steps to Reproduce
Run Forward Tool with controls and states from the CMC output reference

### Expected result
Forward tool runs

### Actual result
Tool execution fails

### Environment and GUI version
Windows 10, Animation Fix GUI

**Comment by aseth1** [comment]
I had to massage the setup file and change the external loads to exclude kinematics for ground reaction force (can we please eliminate this option in the GUI!)  and was able to run on my 4.0 build with no problems.  Loading the same setup file in the GUI and running terminates as observed above.

The messages are expected because a CorrectionController is being added by the ForwardTool and it adds its own actuators (correctors) if they are not present. It is simply informing the user of what it is doing.

**Comment by aymanhab** [comment]
@aseth1 Please commit the "massaged" file to the models repo if possible so it works out of the box. If the messages from the Controller are for debugging, it would be good to hide them by default to avoid the clutter and confusing users who don't know if these are errors, warnings or info messages. If kinematics for external loads need to be removed altogether then please remove from API side then GUI will remove, to avoid having a flag affecting the tool not being accessible from GUI.

**Comment by aseth1** [comment]
@aymanhab all I did was change the paths to to files to the OutputReference and removed the kinematics for ExternalLoads. I can post the exact setup here when I on campus, but I will not push to the repo since we don't want to point to the OutputReference, or do we?

The kinematics for external loads field should be removed immediately from the GUI IMHO to avoid the repeated use. We may want the field remain in the API for "backwards compatibility" and show a warning, but I am happy to remove from Tools and `ExternalLoads`  if that is what the team decides.

**Comment by aseth1** [comment]
@aymanhab my setup and updated external loads file attached:
[subject01_Setup_Forward_40.zip](https://github.com/opensim-org/opensim-gui/files/1812927/subject01_Setup_Forward_40.zip)

**Comment by aseth1** [comment]
This issue appears to be with the `ExternalLoads` and being unable to configure it correctly in the GUI.

If Itry to edit the `ExternalForces` I get:
```
java.lang.RuntimeException: ModelComponent::getModel(): component 'right' of type ExternalForce does not belong to a model. Have you called Model::initSystem()?
	at org.opensim.modeling.opensimSimulationJNI.ModelComponent_getModel(Native Method)
	at org.opensim.modeling.ModelComponent.getModel(ModelComponent.java:65)
	at org.opensim.tracking.EditOneForceJPanel.initComboBoxes(EditOneForceJPanel.java:529)
	at org.opensim.tracking.EditOneForceJPanel.<init>(EditOneForceJPanel.java:69)
	at org.opensim.tracking.EditExternalLoadsPanel.jButtonEditActionPerformed(EditExternalLoadsPanel.java:535)
	at org.opensim.tracking.EditExternalLoadsPanel.access$700(EditExternalLoadsPanel.java:59)
	at org.opensim.tracking.EditExternalLoadsPanel$8.actionPerformed(EditExternalLoadsPanel.java:413)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1086)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1136)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1108)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:131)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
	at org.openide.util.Mutex.readAccess(Mutex.java:218)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1093)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.opensim.tracking.ActuatorsAndExternalLoadsPanel.jEditExternalForceSetButtonActionPerformed(ActuatorsAndExternalLoadsPanel.java:390)
	at org.opensim.tracking.ActuatorsAndExternalLoadsPanel.access$600(ActuatorsAndExternalLoadsPanel.java:64)
	at org.opensim.tracking.ActuatorsAndExternalLoadsPanel$7.actionPerformed(ActuatorsAndExternalLoadsPanel.java:254)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Starting fresh one can select the grf.mot file but cannot add `ExternalForce`s:
![image](https://user-images.githubusercontent.com/6494122/37934373-d44c31d6-3102-11e8-9767-80ac35cf3e68.png)

**Comment by aseth1** [comment]
I verified a couple of times that this setup work on the command line but not in the GUI for the same 0326_01 build.
[subject01_Setup_Forward_40.xml.txt](https://github.com/opensim-org/opensim-gui/files/1849782/subject01_Setup_Forward_40.xml.txt)

**Comment by aymanhab** [comment]
Some feedback:
1. Changing file names without opening the definition of ExternalLoads works just fine in GUI as in the API.
2. Trying to open the external loads edit dialog throws an exception, explanation below:
-- old code from GUI/3.3
` _externalLoads =new ExternalLoads(model, externalLoadsFilename);`
... New code from API driver in 4.0 
`_externalLoads = ExternalLoads(aModel, aExternalLoadsFileName);
aModel.finalizeFromProperties();
_externalLoads.invokeConnectToModel(aModel);`
We should discuss how to upgrade the GUI code without undesirable side-effects.

**Comment by jenhicks** [comment]
Will require changes in the model repo

**Comment by jimmyDunne** [comment]
When the correctionController() is deleted from the forward setup file, the forward tool runs. The initial cause of this issue (external loads) has also been fixed. I will mark this as verified.

**Comment by jenhicks** [comment]
I am able to run without issue on Mac.
