### ISSUE TITLE
Installer "Failed" but OpenSim installs anyways

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#635]
### Steps to reproduce
Created a new user account.
Install Mac .pkg from [here](https://www.dropbox.com/s/ayu7407c1ssrjbk/OpenSim-4.0.Beta.Workshop201803.pkg?dl=0) 

### Expected result
Installs without error/failure.

### Actual result
Installer reports that install failed.
Quit installer. But, I now see OpenSim on launchpad.
Launching OpenSim I see the little red circle. Expanding provides the following message:
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:326)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:384)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[catch] at org.eclipse.jetty.JettyMain.startServer(JettyMain.java:87)
	at org.eclipse.jetty.JettyMain.main(JettyMain.java:55)
	at org.opensim.view.pub.ViewDB$1VizWorker.construct(ViewDB.java:2197)
	at org.opensim.swingui.SwingWorker$2.run(SwingWorker.java:130)
	at java.lang.Thread.run(Thread.java:748)

### Environment and GUI version
Mac. Link above. 

Verified it is local installation (not one from another user).
<img width="1128" alt="screen shot 2018-03-27 at 10 07 53 pm" src="https://user-images.githubusercontent.com/6494122/38009901-778c5912-320b-11e8-9f8a-78be1b53a0d6.png">

**Comment by aymanhab** [comment]
@aseth1 The bind/in-use message occurs when you have multiple instances of the GUI concurrently open since the "servers" from all instances use the same port. This has nothing to do with installer which doesn't run any servers, just copies/unpacks files.

**Comment by chrisdembia** [comment]
You could copy the content at the *end* of `/var/log/installer.log` to get the Mac's Installer log.

**Comment by jenhicks** [comment]
Is there an issue to fix for this one?
