### ISSUE TITLE
java.io.FileNotFoundException on startup and java.lang.UnsatisfiedLinkError when attempting to open a model

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#763]
### Steps to reproduce
*File > Open Model...*, select Models\Gait10dof18musc\OutputReference\subject01.osim.

### Expected result
Model opens.

### Actual result
<pre>
java.lang.UnsatisfiedLinkError: org.opensim.modeling.opensimCommonJNI.ComponentsList_begin__SWIG_0(JLorg/opensim/modeling/ComponentsList;)J
	at org.opensim.modeling.opensimCommonJNI.ComponentsList_begin__SWIG_0(Native Method)
	at org.opensim.modeling.ComponentsList.begin(ComponentsList.java:47)
	at org.opensim.view.NavigatorByTypeModel.buildCollections(NavigatorByTypeModel.java:104)
	at org.opensim.view.NavigatorByTypeModel.<init>(NavigatorByTypeModel.java:96)
	at org.opensim.view.nodes.OneModelNode.<init>(OneModelNode.java:46)
	at org.opensim.view.ExplorerTopComponent.update(ExplorerTopComponent.java:308)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:155)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:143)
	at org.opensim.view.FileOpenOsimModelAction$2.run(FileOpenOsimModelAction.java:101)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>

### Environment and GUI version
AppVeyor artifact OpenSim-b4cabd07-2018-05-17-win64.exe

**Comment by aymanhab** [comment]
Need some context: path, plugins involved.

**Comment by tkuchida** [comment]
No plugins involved. I downloaded the AppVeyor artifact to my desktop and installed to a directory residing in the same parent directory as all the other betas (but with a unique directory name). No errors/warnings during installation. I then started OpenSim, installed resources by typing "installResources()" in the ScriptingShell window, and attempted to open a model. I think I followed all the same steps as for previous versions, so I'm not really sure what I'm looking for. If you think this is a local issue, I can test on a different machine later today.

**Comment by aymanhab** [comment]
Tom, not sure if new mechanism to load falls by Chris is in, if not did you
change your path otherwise?

**Comment by chrisdembia** [comment]
> Tom, not sure if new mechanism to load falls by Chris is in, if not did you
change your path otherwise?

No it has not been merged.

**Comment by tkuchida** [comment]
> did you change your path otherwise?

No, I have not changed my path. Anyway, I thought that OpenSim no longer relied on the path :confused:

**Comment by aymanhab** [comment]
It shouldn't but you broke it for the first time in years 😀

**Comment by tkuchida** [comment]
Ok, if it's something I did locally, then don't worry about it; I'll try to figure it out over the weekend.

**Comment by aymanhab** [comment]
If you execute one of the executables in bin folder on command line you may
get more information. I'll try to download and run from appveyor myself.

**Comment by chrisdembia** [comment]
This could be related to https://github.com/opensim-org/opensim-core/pull/2176

**Comment by aymanhab** [comment]
That's why we need to see the actual missing symbol. Dependency walker may do it or an executable that loads the dlls including java test cases

**Comment by aymanhab** [comment]
You were right Chris, can you undo the change and force Gui rebuild. Or let me know and I'll do it. Thanks

**Comment by chrisdembia** [comment]
@aymanhab are you sure it isn't because `.java` files in the GUI need to be synced up? Perhaps there are lingering `*.java` files that should be deleted.

**Comment by tkuchida** [comment]
I downloaded the AppVeyor artifact again and reinstalled. This time, I noticed the following :red_circle: `FileNotFoundException` Exceptions immediately after opening the GUI for the first time (the :red_circle: may have been there on startup last night and I just didn't notice it).

<pre>
java.io.FileNotFoundException: C:\Users\tkuchida\OpenSim 4.0 appveyor _180517\OpenSim b4cabd07-2018-05-17\platform\modules\org-netbeans-core-ui.jar (The system cannot find the path specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
	at org.netbeans.core.startup.layers.BinaryFS$BFSFile.getInputStream(BinaryFS.java:906)
Caused: java.io.FileNotFoundException: Cannot find 'jar:file:/C:/Users/tkuchida/OpenSim%204.0%20appveyor%20_180517/OpenSim%20b4cabd07-2018-05-17/platform/modules/org-netbeans-core-ui.jar!/org/netbeans/core/ui/resources/SwingBrowser.xml'
	at org.netbeans.core.startup.layers.BinaryFS$BFSFile.getInputStream(BinaryFS.java:909)
	at org.openide.filesystems.MultiFileObject.getInputStream(MultiFileObject.java:666)
	at org.openide.filesystems.MultiFileObject.getInputStream(MultiFileObject.java:666)
	at org.netbeans.modules.openide.loaders.FileEntityResolver$DTDParser.parse(FileEntityResolver.java:419)
Caused: java.io.IOException: Parsing MultiFileObject@44d8d175[Services/Browsers/SwingBrowser.settings]: Cannot find 'jar:file:/C:/Users/tkuchida/OpenSim%204.0%20appveyor%20_180517/OpenSim%20b4cabd07-2018-05-17/platform/modules/org-netbeans-core-ui.jar!/org/netbeans/core/ui/resources/SwingBrowser.xml'
	at org.netbeans.modules.openide.loaders.FileEntityResolver$DTDParser.parse(FileEntityResolver.java:449)
	at org.netbeans.modules.openide.loaders.FileEntityResolver.getEnvForIDO(FileEntityResolver.java:175)
	at org.netbeans.modules.openide.loaders.FileEntityResolver.getEnvironment(FileEntityResolver.java:168)
	at org.openide.loaders.Environment.findForOne(Environment.java:131)
	at org.openide.loaders.InstanceDataObject.getCookiesLookup(InstanceDataObject.java:714)
	at org.openide.loaders.InstanceDataObject.getCookiesLookup(InstanceDataObject.java:705)
	at org.openide.loaders.InstanceDataObject.getCookieFromEP(InstanceDataObject.java:622)
	at org.openide.loaders.InstanceDataObject.getCookie(InstanceDataObject.java:652)
	at org.openide.loaders.FolderInstance.acceptDataObject(FolderInstance.java:417)
	at org.openide.loaders.FolderInstance.defaultProcessObjects(FolderInstance.java:798)
	at org.openide.loaders.FolderInstance.access$000(FolderInstance.java:103)
	at org.openide.loaders.FolderInstance$1R.init(FolderInstance.java:693)
	at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:728)
	at org.openide.loaders.FolderLookup.postCreationTask(FolderLookup.java:260)
	at org.openide.loaders.FolderInstance.processObjects(FolderInstance.java:770)
	at org.openide.loaders.FolderInstance$Listener.finished(FolderInstance.java:1059)
	at org.openide.loaders.FolderList.createBoth(FolderList.java:879)
	at org.openide.loaders.FolderList.getObjects(FolderList.java:564)
	at org.openide.loaders.FolderList.access$600(FolderList.java:77)
	at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:963)
	at org.openide.loaders.FolderList$ListTask.run(FolderList.java:939)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.openide.util.RequestProcessor$Processor.doEvaluate(RequestProcessor.java:2111)
	at org.openide.util.RequestProcessor$Task.waitFinished(RequestProcessor.java:1675)
	at org.openide.loaders.FolderInstance.waitFinished(FolderInstance.java:332)
	at org.openide.loaders.FolderInstance.instanceCreate(FolderInstance.java:281)
	at org.openide.loaders.FolderLookup.instanceForCookie(FolderLookup.java:222)
	at org.openide.loaders.FolderInstance$HoldInstance.instanceCreate(FolderInstance.java:1157)
	at org.openide.loaders.FolderLookup.createInstance(FolderLookup.java:166)
	at org.openide.loaders.FolderInstance.defaultProcessObjectsFinal(FolderInstance.java:888)
	at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:730)
	at org.openide.loaders.FolderLookup.postCreationTask(FolderLookup.java:260)
	at org.openide.loaders.FolderInstance.processObjects(FolderInstance.java:770)
	at org.openide.loaders.FolderInstance$Listener.finished(FolderInstance.java:1059)
	at org.openide.loaders.FolderList.createBoth(FolderList.java:879)
	at org.openide.loaders.FolderList.getObjects(FolderList.java:564)
	at org.openide.loaders.FolderList.access$600(FolderList.java:77)
	at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:963)
	at org.openide.loaders.FolderList$ListTask.run(FolderList.java:939)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
</pre>

<pre>
java.io.FileNotFoundException: C:\Users\tkuchida\OpenSim 4.0 appveyor _180517\OpenSim b4cabd07-2018-05-17\ide\modules\org-netbeans-modules-xml-catalog.jar (The system cannot find the path specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:109)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
	at org.netbeans.core.startup.layers.BinaryFS$BFSFile.getInputStream(BinaryFS.java:906)
Caused: java.io.FileNotFoundException: Cannot find 'jar:file:/C:/Users/tkuchida/OpenSim%204.0%20appveyor%20_180517/OpenSim%20b4cabd07-2018-05-17/ide/modules/org-netbeans-modules-xml-catalog.jar!/org/netbeans/modules/xml/catalog/resources/ProjectSettings.xml'
	at org.netbeans.core.startup.layers.BinaryFS$BFSFile.getInputStream(BinaryFS.java:909)
	at org.openide.filesystems.MultiFileObject.getInputStream(MultiFileObject.java:666)
	at org.openide.filesystems.MultiFileObject.getInputStream(MultiFileObject.java:666)
	at org.netbeans.modules.openide.loaders.FileEntityResolver$DTDParser.parse(FileEntityResolver.java:419)
Caused: java.io.IOException: Parsing MultiFileObject@23dba73e[Services/Hidden/org-netbeans-modules-xml-catalog-settings-CatalogSettings.settings]: Cannot find 'jar:file:/C:/Users/tkuchida/OpenSim%204.0%20appveyor%20_180517/OpenSim%20b4cabd07-2018-05-17/ide/modules/org-netbeans-modules-xml-catalog.jar!/org/netbeans/modules/xml/catalog/resources/ProjectSettings.xml'
	at org.netbeans.modules.openide.loaders.FileEntityResolver$DTDParser.parse(FileEntityResolver.java:449)
	at org.netbeans.modules.openide.loaders.FileEntityResolver.getEnvForIDO(FileEntityResolver.java:175)
	at org.netbeans.modules.openide.loaders.FileEntityResolver.getEnvironment(FileEntityResolver.java:168)
	at org.openide.loaders.Environment.findForOne(Environment.java:131)
	at org.openide.loaders.InstanceDataObject.getCookiesLookup(InstanceDataObject.java:714)
	at org.openide.loaders.InstanceDataObject.getCookiesLookup(InstanceDataObject.java:705)
	at org.openide.loaders.InstanceDataObject.getCookieFromEP(InstanceDataObject.java:622)
	at org.openide.loaders.InstanceDataObject.getCookie(InstanceDataObject.java:652)
	at org.openide.loaders.FolderInstance.acceptDataObject(FolderInstance.java:417)
	at org.openide.loaders.FolderInstance.defaultProcessObjects(FolderInstance.java:798)
	at org.openide.loaders.FolderInstance.access$000(FolderInstance.java:103)
	at org.openide.loaders.FolderInstance$1R.init(FolderInstance.java:693)
	at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:728)
	at org.openide.loaders.FolderLookup.postCreationTask(FolderLookup.java:260)
	at org.openide.loaders.FolderInstance.processObjects(FolderInstance.java:770)
	at org.openide.loaders.FolderInstance$Listener.finished(FolderInstance.java:1059)
	at org.openide.loaders.FolderList.createBoth(FolderList.java:879)
	at org.openide.loaders.FolderList.getObjects(FolderList.java:564)
	at org.openide.loaders.FolderList.access$600(FolderList.java:77)
	at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:963)
	at org.openide.loaders.FolderList$ListTask.run(FolderList.java:939)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.openide.util.RequestProcessor$Processor.doEvaluate(RequestProcessor.java:2111)
	at org.openide.util.RequestProcessor$Task.waitFinished(RequestProcessor.java:1675)
	at org.openide.loaders.FolderInstance.waitFinished(FolderInstance.java:332)
	at org.openide.loaders.FolderInstance.instanceCreate(FolderInstance.java:281)
	at org.openide.loaders.FolderLookup.instanceForCookie(FolderLookup.java:222)
	at org.openide.loaders.FolderInstance$HoldInstance.instanceCreate(FolderInstance.java:1157)
	at org.openide.loaders.FolderLookup.createInstance(FolderLookup.java:166)
	at org.openide.loaders.FolderInstance.defaultProcessObjectsFinal(FolderInstance.java:888)
	at org.openide.loaders.FolderInstance$1R.run(FolderInstance.java:730)
	at org.openide.loaders.FolderLookup.postCreationTask(FolderLookup.java:260)
	at org.openide.loaders.FolderInstance.processObjects(FolderInstance.java:770)
	at org.openide.loaders.FolderInstance$Listener.finished(FolderInstance.java:1059)
	at org.openide.loaders.FolderList.createBoth(FolderList.java:879)
	at org.openide.loaders.FolderList.getObjects(FolderList.java:564)
	at org.openide.loaders.FolderList.access$600(FolderList.java:77)
	at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:963)
	at org.openide.loaders.FolderList$ListTask.run(FolderList.java:939)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
</pre>

**Comment by aymanhab** [comment]
I don't think so, those would not compile to begin with since their native implementation in the jni classes would be missing. Doesn't automated build copy these?

**Comment by chrisdembia** [comment]
@aymanhab I've opened https://github.com/opensim-org/opensim-core/pull/2194

**Comment by chrisdembia** [comment]
> I don't think so, those would not compile to begin with since their native implementation in the jni classes would be missing.

I'm not sure I follow.

> Doesn't automated build copy these?

yes but some `.java` files need to be deleted.

**Comment by chrisdembia** [comment]
Ah okay I understand now. Thanks for explaining.
