### ISSUE TITLE
Opening a model on Mac cases an exception

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-gui#779]
### Steps to reproduce
Install OpenSim on Mac, open a model

### Expected result
model opens 
### Actual result
🔴  
![red_circle](https://user-images.githubusercontent.com/5296507/40509968-0282dd72-5f50-11e8-8872-2dede4f29e7b.png)

`
java.lang.UnsatisfiedLinkError: org.opensim.modeling.opensimCommonJNI.ComponentsList_begin(JLorg/opensim/modeling/ComponentsList;)J
	at org.opensim.modeling.opensimCommonJNI.ComponentsList_begin(Native Method)
	at org.opensim.modeling.ComponentsList.begin(ComponentsList.java:47)
	at org.opensim.view.NavigatorByTypeModel.buildCollections(NavigatorByTypeModel.java:104)
	at org.opensim.view.NavigatorByTypeModel.<init>(NavigatorByTypeModel.java:96)
	at org.opensim.view.nodes.OneModelNode.<init>(OneModelNode.java:46)
	at org.opensim.view.ExplorerTopComponent.update(ExplorerTopComponent.java:308)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:155)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:143)
	at org.opensim.view.FileOpenOsimModelAction$2.run(FileOpenOsimModelAction.java:101)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

### Environment and GUI version
OpenSim 5eacd8a-2018-05-22 
Mac

**Comment by tkuchida** [comment]
Related to #763

**Comment by aymanhab** [comment]
Thanks for reporting @jimmyDunne Yes that's a build problem that I'm investigating at the moment.

**Comment by aymanhab** [comment]
Likely will be fixed by https://github.com/opensim-org/opensim-core/pull/2194 in the pipe

**Comment by aymanhab** [comment]
Fixed in latest build
