### ISSUE TITLE
Double-clicking bodies eventually causes GUI to enter infinite loop

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#829]
### Steps to reproduce
- open a model
- double-click objects in Visualizer window

### Expected result
Selection is indicated graphically, camera is centered on selected object, camera rotation now occurs about center of selected object's bounding box, navigator panel highlights selected object.

### Actual result
GUI eventually enters infinite loop, automatically cycling between selecting two or more bodies, and cannot be stopped.

![](https://user-images.githubusercontent.com/4203505/40881505-1ef5846c-667d-11e8-9b85-ac4295fadb7d.gif)

### Environment and GUI version
AppVeyor artifact OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by jenhicks** [comment]
I tried for a while on my Mac, but couldn't reproduce.

**Comment by tkuchida** [comment]
@aymanhab I was able to reproduce using OpenSim-1e476f28-2018-06-13-win64.exe from Dropbox (the "OpenSim 4.0 User Session and Tutorial" version; no local modifications) as follows:
- open 2392 model from Resources directory
- zoom into head/torso
- (using mouse) single-click skull, single-click spine, single-click skull, etc., repeating quickly

I've also encountered the issue without deliberately clicking quickly, but I don't recall what I was doing at the time (probably adjust the camera). As far as I can tell, the only way to break the infinite loop is to close the model, whereupon I get a :red_circle: `NullPointerException`:
<pre>
java.lang.NullPointerException
	at org.opensim.view.pub.ViewDB.markSelected(ViewDB.java:1095)
	at org.opensim.view.pub.ViewDB.setSelectedObject(ViewDB.java:1158)
	at org.opensim.threejs.JSONMessageHandler$1.run(JSONMessageHandler.java:56)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>
