### ISSUE TITLE
IllegalComponentStateException thrown after showing/hiding muscles and changing coordinate values

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#830]
### Steps to reproduce
Not sure exactly what's happening, but I've been getting this exception consistently when trying to inspect muscle paths as conditional path points turn on and off.

### Expected result
Muscles can be shown/hidden and coordinate values can be modified without throwing Exceptions.

### Actual result
<pre>
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2062)
	at java.awt.Component.getLocationOnScreen(Component.java:2036)
	at javax.swing.text.JTextComponent$InputMethodRequestsHandler.getTextLocation(JTextComponent.java:4643)
	at sun.awt.im.InputMethodContext.getTextLocation(InputMethodContext.java:278)
	at sun.awt.windows.WInputMethod$1.run(WInputMethod.java:588)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>

![](https://user-images.githubusercontent.com/4203505/40882711-226700ae-669f-11e8-82ca-c608d64981c0.gif)

### Environment and GUI version
AppVeyor artifact OpenSim-cedd8d22-2018-05-31-win64.exe

**Comment by aymanhab** [comment]
@tkuchida which model is this to reproduce? Thanks

**Comment by tkuchida** [comment]
> which model is this to reproduce? Thanks

See Messages window in GIF.

**Comment by aymanhab** [comment]
While I don't dispute the movie being authentic, the stacktrace has nothing to do with our code! and it doesn't reproduce in my environment.

**Comment by tkuchida** [comment]
> While I don't dispute the movie being authentic, the stacktrace has nothing to do with our code! and it doesn't reproduce in my environment.

I'm not making this up but if the problem can't be isolated, it can't be fixed.
