### ISSUE TITLE
bad marshal data error installing Opensim 4.0 Beta with Python 3.6.5, Windows 7 x64

### ISSUE THREAD

**Issue by marnunez** [opensim-org/opensim-gui#886]
### Steps to reproduce

`python setup.py install`

### Expected result

Correct installation of python wrapper

### Actual result

```
"c:\ProgramData\Miniconda3\python.exe" setup.py install
running install
running bdist_egg
running egg_info
writing opensim.egg-info\PKG-INFO
writing dependency_links to opensim.egg-info\dependency_links.txt
writing top-level names to opensim.egg-info\top_level.txt
reading manifest file 'opensim.egg-info\SOURCES.txt'
writing manifest file 'opensim.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying opensim.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying opensim.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying opensim.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying opensim.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    'Topic :: Scientific/Engineering :: Physics',
  File "c:\ProgramData\Miniconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "c:\ProgramData\Miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\ProgramData\Miniconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\ProgramData\Miniconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "c:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "c:\ProgramData\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\ProgramData\Miniconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "c:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "c:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "c:\ProgramData\Miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

```
### Environment and GUI version

Windows 7 x64, python 3.6.5
OpenSIM 4.0 Beta b435c8fa-2018-07-06

**Comment by chrisdembia** [comment]
Hey @marnunez. The python package that comes with the OpenSim binaries you downloaded is for python 2.7, not python 3.

**Comment by chrisdembia** [comment]
Please close this issue if you're able to solve your issue by using python 2.7 (64-bit) instead.

**Comment by marnunez** [comment]
Ok. I'll test it now in another PC. I hoped to keep OpenSIM 3.3 wrapper in Python 2.7 and 4.0's wrapper in Python 3, keeping the best of both worlds. Any reason why you're sticking with Python 2.x for the beta installer?

**Comment by chrisdembia** [comment]
I would be okay with using Python 3 instead.
